apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: RELATED_IMAGE_FEATURE_SERVER
          value: quay.io/feastdev/feature-server:0.66.0
        - name: RELATED_IMAGE_CRON_JOB
          value: quay.io/openshift/origin-cli:4.17
        - name: RELATED_IMAGE_ODH_KUBE_RBAC_PROXY_IMAGE
          value: quay.io/opendatahub/odh-kube-rbac-proxy@sha256:acd9de62b8339dbacd39635317e5e596e09a70ae26ac9eccdde4a4124388740f
